services:
  jenkins:
    build: .
    image: jenkins:jdk21
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      # Jenkins home directory
      - /tmp/jenkins_home:/var/jenkins_home
      # Mount the host Docker socket to talk to the host daemon
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
